version: 0.2

env:
  parameter-store:
    USERNAME: /myapp/docker-credentials/username
    PASSWORD: /myapp/docker-credentials/password

        
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - node --version
      - echo "installed node "
    # steps:
  pre_build:
    commands:
      - npm install
      - echo "dependencies installed"
  build:
    commands:
      - docker build -t alizain4653/netflix-react-app:latest .
  post_build:
    commands:
      - echo "waiting right now"
      - docker login -u $USERNAME -p $PASSWORD
      - docker push alizain4653/netflix-react-app:latest
artifacts:
  files:
    - '**/*'
  base-directory: "./"
  name: build-artifact-name
  discard-paths: no
